# Nombre del microservicio
spring.application.name=backend-core

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MONGODB)
# ==========================================
spring.mongodb.uri=${MONGO_URL:${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}}# ==========================================

spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/db_gestion_procesos}
# CONFIGURACIÓN DE RED (PUERTO)
# ==========================================
server.port=${PORT:8080}

# ==========================================
# LOGS DE DEPURACIÓN (MODO DETECTIVE)
# ==========================================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# Silenciar el "ruido" del driver de Mongo (¡MUY IMPORTANTE en Railway!)
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

# Desactivar el reporte de autoconfiguración inicial
logging.level.org.springframework.boot.autoconfigure.logging=INFO

# Web y servidor en modo estándar
logging.level.org.apache.tomcat=INFO
logging.level.org.springframework.web=INFO

# ==========================================
# CONFIGURACIÓN JWT
# ==========================================
# Usa una variable de entorno en producción, o el valor por defecto en local
jwt.secret=${JWT_SECRET:404e635266556a586e3272357538782F413f4428472b4b6250655368566d5971}
# Tiempo de expiración del token (ej. 24 horas en milisegundos)
jwt.expiration=86400000

management.endpoints.web.exposure.include=mappings

# ==========================================
# CONFIGURACIÓN DE AWS S3
# ==========================================
# Se extraen de variables de entorno en la nube. EN LOCAL debes configurarlas en tu IDE.
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION:us-east-2}
aws.s3.bucket.name=${AWS_BUCKET_NAME:uagrm-gestion-archivos-beimar}

# ==========================================
# CONFIGURACIONES GENERALES Y MULTIPART
# ==========================================
spring.data.mongodb.auto-index-creation=true

# Tamaño máximo permitido para un solo archivo
spring.servlet.multipart.max-file-size=10MB

# Tamaño máximo permitido para la petición completa
spring.servlet.multipart.max-request-size=50MB

# ==========================================
# CONFIGURACIÓN DE SPRING AI (LOCAL / OLLAMA O LM STUDIO)
# ==========================================
spring.ai.openai.base-url=${SPRING_AI_BASE_URL:http://localhost:5000}
spring.ai.openai.api-key=${SPRING_AI_API_KEY:local-key}
spring.ai.openai.chat.options.model=${SPRING_AI_MODEL:gemma-2-2b-it}